# Generated by Django 4.0.5 on 2022-06-27 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_fullname_alter_usermodel_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='follower',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
